name: Linter Checkout
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install deps
        run: make install-deps
      - name: Run linter
        run: make lint
